sudo: false
cache:
  go: true
  directories:
    - $HOME/.cache
    - $HOME/gopath/pkg/mod
language: go
go:
  - "1.11"
  - "1.12"
  - 1.x
env:
  - GO111MODULE=on

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.16.0

script:
  - go fmt ./...
  - go fix ./...
  - go mod tidy && git diff --exit-code
  - golangci-lint run
  - go test -v -mod=vendor -bench=. -covermode=atomic -coverprofile=coverage.txt -race
before_cache: rm -f $HOME/.cache/go-build/log.txt

after_success: bash <(curl -s https://codecov.io/bash)
